/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as DesignNewRouteImport } from './routes/design/new'
import { Route as DesignIdGeneratingRouteImport } from './routes/design/$id/generating'
import { Route as DesignIdPreferencesRouteImport } from './routes/design/$id/preferences'
import { Route as DesignIdRoomsRouteImport } from './routes/design/$id/rooms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignNewRoute = DesignNewRouteImport.update({
  id: '/design/new',
  path: '/design/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIdGeneratingRoute = DesignIdGeneratingRouteImport.update({
  id: '/design/$id/generating',
  path: '/design/$id/generating',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIdPreferencesRoute = DesignIdPreferencesRouteImport.update({
  id: '/design/$id/preferences',
  path: '/design/$id/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIdRoomsRoute = DesignIdRoomsRouteImport.update({
  id: '/design/$id/rooms',
  path: '/design/$id/rooms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/design/new': typeof DesignNewRoute
  '/design/$id/generating': typeof DesignIdGeneratingRoute
  '/design/$id/preferences': typeof DesignIdPreferencesRoute
  '/design/$id/rooms': typeof DesignIdRoomsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/design/new': typeof DesignNewRoute
  '/design/$id/generating': typeof DesignIdGeneratingRoute
  '/design/$id/preferences': typeof DesignIdPreferencesRoute
  '/design/$id/rooms': typeof DesignIdRoomsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/design/new': typeof DesignNewRoute
  '/design/$id/generating': typeof DesignIdGeneratingRoute
  '/design/$id/preferences': typeof DesignIdPreferencesRoute
  '/design/$id/rooms': typeof DesignIdRoomsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/projects'
    | '/register'
    | '/design/new'
    | '/design/$id/generating'
    | '/design/$id/preferences'
    | '/design/$id/rooms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/projects'
    | '/register'
    | '/design/new'
    | '/design/$id/generating'
    | '/design/$id/preferences'
    | '/design/$id/rooms'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/projects'
    | '/register'
    | '/design/new'
    | '/design/$id/generating'
    | '/design/$id/preferences'
    | '/design/$id/rooms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRoute
  RegisterRoute: typeof RegisterRoute
  DesignNewRoute: typeof DesignNewRoute
  DesignIdGeneratingRoute: typeof DesignIdGeneratingRoute
  DesignIdPreferencesRoute: typeof DesignIdPreferencesRoute
  DesignIdRoomsRoute: typeof DesignIdRoomsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/new': {
      id: '/design/new'
      path: '/design/new'
      fullPath: '/design/new'
      preLoaderRoute: typeof DesignNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/$id/generating': {
      id: '/design/$id/generating'
      path: '/design/$id/generating'
      fullPath: '/design/$id/generating'
      preLoaderRoute: typeof DesignIdGeneratingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/$id/preferences': {
      id: '/design/$id/preferences'
      path: '/design/$id/preferences'
      fullPath: '/design/$id/preferences'
      preLoaderRoute: typeof DesignIdPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/$id/rooms': {
      id: '/design/$id/rooms'
      path: '/design/$id/rooms'
      fullPath: '/design/$id/rooms'
      preLoaderRoute: typeof DesignIdRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRoute,
  RegisterRoute: RegisterRoute,
  DesignNewRoute: DesignNewRoute,
  DesignIdGeneratingRoute: DesignIdGeneratingRoute,
  DesignIdPreferencesRoute: DesignIdPreferencesRoute,
  DesignIdRoomsRoute: DesignIdRoomsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
